
version: "3.7"
services:
  jenkins:
    container_name: jenkins-local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-log:/var/log/jenkins
      - /var/run/docker.sock:/var/run/docker.sock

volumes: 
  jenkins-data:
    name: jenkins-data
  jenkins-log: 
    name: jenkins-log